services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: {{APP_NAME}}_app
    restart: always
    volumes:
      - data:/data
    environment:
      - VIRTUAL_HOST={{DOMAIN}}
      - LETSENCRYPT_HOST={{DOMAIN}}
      - LETSENCRYPT_EMAIL={{EMAIL}}
      - VIRTUAL_PORT=80
      - WEBSOCKET_ENABLED=true
    networks:
      - proxy-net

volumes:
  data:

networks:
  proxy-net:
    external: true
