services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: {{APP_NAME}}_app
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/app/data
    environment:
      - VIRTUAL_HOST={{DOMAIN}}
      - LETSENCRYPT_HOST={{DOMAIN}}
      - LETSENCRYPT_EMAIL={{EMAIL}}
      - VIRTUAL_PORT=3001
    networks:
      - proxy-net

volumes:
  data:

networks:
  proxy-net:
    external: true
