services:
  easyimage:
    image: ghcr.io/lovebai/easyimage2.0-f:latest
    container_name: {{APP_NAME}}_app
    restart: unless-stopped
    volumes:
      - data:/app/web/config
      - data:/app/web/i
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
      - DEBUG=false
      - VIRTUAL_HOST={{DOMAIN}}
      - LETSENCRYPT_HOST={{DOMAIN}}
      - LETSENCRYPT_EMAIL={{EMAIL}}
      - VIRTUAL_PORT=80
    networks:
      - proxy-net

volumes:
  data:
  data:

networks:
  proxy-net:
    external: true
