services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: {{APP_NAME}}_app
    restart: always
    volumes:
      - data:/srv
      - db:/database
      - config:/config
    environment:
      - VIRTUAL_HOST={{DOMAIN}}
      - LETSENCRYPT_HOST={{DOMAIN}}
      - LETSENCRYPT_EMAIL={{EMAIL}}
      - VIRTUAL_PORT=80
    networks:
      - proxy-net

volumes:
  data:
  db:
  config:

networks:
  proxy-net:
    external: true
