services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: {{APP_NAME}}_app
    restart: always
    environment:
      - VIRTUAL_HOST={{DOMAIN}}
      - LETSENCRYPT_HOST={{DOMAIN}}
      - LETSENCRYPT_EMAIL={{EMAIL}}
      - VIRTUAL_PORT=80
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
