services:
  alist:
    image: xhofe/alist:latest
    container_name: {{APP_NAME}}_app
    restart: always
    volumes:
      - data:/opt/alist/data
    environment:
      - VIRTUAL_HOST={{DOMAIN}}
      - LETSENCRYPT_HOST={{DOMAIN}}
      - LETSENCRYPT_EMAIL={{EMAIL}}
      - VIRTUAL_PORT=5244
    networks:
      - proxy-net

volumes:
  data:

networks:
  proxy-net:
    external: true
