services:
  # --- 兰空图床主程序 ---
  lsky-pro:
    image: halcyonazure/lsky-pro-docker:latest
    container_name: {{APP_NAME}}_app
    restart: always
    environment:
      - VIRTUAL_HOST={{DOMAIN}}
      - LETSENCRYPT_HOST={{DOMAIN}}
      - LETSENCRYPT_EMAIL={{EMAIL}}
      - VIRTUAL_PORT=80
    volumes:
      - web_data:/var/www/html
    depends_on:
      - db
    networks:
      - proxy-net
      - default

  # --- 专用数据库 ---
  db:
    image: mariadb:10.6
    container_name: {{APP_NAME}}_db
    restart: always
    environment:
      - MYSQL_DATABASE=lsky
      - MYSQL_USER=lsky
      - MYSQL_PASSWORD=lsky_password
      - MYSQL_ROOT_PASSWORD=lsky_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

volumes:
  web_data:
  db_data:

networks:
  proxy-net:
    external: true
